### PR TITLE
Add `call_runtime`example

### PR DESCRIPTION
**Pull request by pmikolajczyk41**
Companion to: https://github.com/paritytech/ink/pull/1641

### CODE REVIEW

**Comment by agryaznov** [comment]
I think for now it should be moved to https://github.com/paritytech/ink/tree/master/integration-tests, first. For sure it would be a useful example, but I suppose we can't make it here until we have it included in the latest release.

**Comment by pmikolajczyk41** [comment]
@agryaznov  Should we keep this PR until `call_runtime` is released, or should we close this for now?

**Comment by agryaznov** [comment]
> Should we keep this PR until call_runtime is released, or should we close this for now?

It shoudn't take much time before we release it. Hence, let's leave this PR open, just being renamed a bit

**Comment by pmikolajczyk41** [comment]
@agryaznov since yesterday ink! 4.0.1 was released, I've bumped the versions here as well, so we should be good to go

**Comment by agryaznov** [comment]
not yet, I think we'll stabilize the host function, first

**Review by agryaznov — CHANGES_REQUESTED** [review]
putting this on hold so far

**Pull request closed without merging**
